#pragma once

#define PLUGIN_VERSION_NUM 2,0,0,0
#define PLUGIN_VERSION_TXT "2.0.0"
#define PLUGIN_VERSION_WTXT L"2.0.0"

#define WINSCP_PLUGIN_VERSION_WTXT L"1.6.2.151"
#define WINSCP_VERSION_WTXT L"4.1.9.0"
#define PUTTY_VERSION_WTXT L"0.61"
#define FILEZILLA_VERSION_WTXT L"2.2.32"
