#pragma once

#define PLUGIN_VERSION_NUM 2,0,1,0
#define PLUGIN_VERSION_TXT "2.0.1"
#define PLUGIN_VERSION_WTXT L"2.0.1"

#define WINSCP_PLUGIN_VERSION_WTXT L"1.6.2.151"
#define WINSCP_VERSION_WTXT L"4.1.9.0"
#define PUTTY_VERSION_WTXT L"0.61"
#define FILEZILLA_VERSION_WTXT L"2.2.32"
#define ZLIB_VERSION_WTXT L"1.2.5"
#define LIBSSH2_VERSION_WTXT L"1.2.8"
#define CURL_VERSION_WTXT L"7.21.7"
#define OPENSSL_VERSION_WTXT L"1.0.0d"
#define BOOST_VERSION_WTXT L"1.48.0"
