#include "src\mfc\objcore.cpp"
// #include "src\mfc\arccore.cpp"
// #include "src\mfc\arcobj.cpp"
// #include "src\mfc\arcex.cpp"
// #include "src\mfc\arcstrm.cpp"
#include "src\mfc\afxglobals.cpp"
#include "src\mfc\except.cpp"
// #include "src\mfc\filetxt.cpp"
// #include "src\mfc\filemem.cpp"
// #include "src\mfc\fileshrd.cpp"
#include "src\mfc\filex.cpp"
#include "src\mfc\filest.cpp"
#include "src\mfc\strcore.cpp"
#include "src\mfc\winstr.cpp"
//#include "src\mfc\winutil.cpp"
#include "src\mfc\fixalloc.cpp"
#include "src\mfc\timecore.cpp"
#include "src\mfc\filecore.cpp"
