// #include "src\mfc\afxinl1.cpp"
#include "src\mfc\afxtls.cpp"
#include "src\mfc\afxasert.cpp"
#include "src\mfc\mtcore.cpp"
#include "src\mfc\array_b.cpp"
// #include "src\mfc\array_p.cpp"
// #include "src\mfc\array_w.cpp"
// #include "src\mfc\list_p.cpp"
#include "src\mfc\map_pp.cpp"
#include "src\mfc\plex.cpp"
// #include "src\mfc\afxinl2.cpp"
// #include "src\mfc\afxinl3.cpp"
#include "src\mfc\validadd.cpp"
#include "src\mfc\appinit.cpp"
#include "src\mfc\appterm.cpp"
// #include "src\mfc\wingdi.cpp"
// #include "src\mfc\wingdix.cpp"
#include "src\mfc\wincore.cpp"
#include "src\mfc\cmdtarg.cpp"
// #include "src\mfc\winocc.cpp"
#include "src\mfc\winhand.cpp"
// #include "src\mfc\winctrl1.cpp"
// #include "src\mfc\appui1.cpp"
// #include "src\mfc\appui2.cpp"
// #include "src\mfc\apphelp.cpp"
#include "src\mfc\olevar.cpp"
#include "src\mfc\olemisc.cpp"
#include "src\mfc\olelock.cpp"
#include "src\mfc\olereg.cpp"
#include "src\mfc\oledisp1.cpp"
#include "src\mfc\oledisp2.cpp"
#include "src\mfc\olecnvrt.cpp"
#include "src\mfc\oletyplb.cpp"
#include "src\mfc\ctlreg.cpp"
#include "src\mfc\auxdata.cpp"
