#ifndef RDESTL_ALLOCATOR_H
#define RDESTL_ALLOCATOR_H

#include <stdlib.h>
#include <nbglobals.h>
#include "rdestl_common.h"

namespace rde
{

// CONCEPT!
class RDESTL_LIB allocator
{
public:
	explicit allocator()	{}
	// Copy ctor generated by compiler.
	// allocator(const allocator &)
	~allocator() {}

	// Generated by compiler.
	//allocator & operator=(const allocator &)

	void * allocate(::size_t bytes, int flags = 0);
	// Not supported for standard allocator for the time being.
	void * allocate_aligned(::size_t bytes, ::size_t alignment, int flags = 0);
	void deallocate(void * ptr, ::size_t bytes);

private:
};

// True if lhs can free memory allocated by rhs and vice-versa.
inline bool operator==(const allocator & /*lhs*/, const allocator & /*rhs*/)
{
	return true;
}
inline bool operator!=(const allocator & lhs, const allocator & rhs)
{
	return !(lhs == rhs);
}

inline void * allocator::allocate(::size_t bytes, int)
{
	// return operator new(bytes);
	return nb::operator_new(bytes);
}

inline void allocator::deallocate(void * ptr, ::size_t)
{
	// operator delete(ptr);
	nb_free(ptr);
}

} // namespace rde

//-----------------------------------------------------------------------------
#endif // #ifndef RDESTL_ALLOCATOR_H
